namespace rwby.core
{
    public enum RubyRoseStates : ushort
    {
        SCYTHE_GRD_5a = 50,
        SCYTHE_GRD_5b,
        SCYTHE_GRD_5bB,
        SCYTHE_GRD_8b,
        SCYTHE_GRD_2c,
        SCYTHE_AIR_5a,
        SCYTHE_AIR_5b,
        SCYTHE_AIR_5c,
        SCYTHE_SPECIAL_Buzzsaw_Ground,
        SCYTHE_SPECIAL_Buzzsaw_Aerial,
        SCYTHE_SPECIAL_ScytheThrow,
        SCYTHE_GRD_8a,
        SCYTHE_GRD_8aA,
        SCYTHE_GRD_8bB,
        SCYTHE_GRD_5c,
        SCYTHE_GRD_5cC,
        SCYTHE_GRD_8c,
        SHARED_TELEPORT_DOWN,
        SCYTHE_AIR_8b,
        SCYTHE_SPECIAL_Buzzsaw_Aerial_End,
        SCYTHE_SPECIAL_SniperStance_Grd_Enter,
        SCYTHE_SPECIAL_SniperStance_Grd,
        SCYTHE_SPECIAL_SniperStance_Grd_A,
        SCYTHE_SPECIAL_SniperStance_Grd_B,
        SCYTHE_SPECIAL_SniperStance_Grd_C,
        SCYTHE_SPECIAL_SniperStance_Grd_J,
        SCYTHE_SPECIAL_SniperStance_Grd_Exit,
        SCYTHE_SPECIAL_SniperStance_Air_Enter,
        SCYTHE_SPECIAL_SniperStance_Air,
        SCYTHE_SPECIAL_SniperStance_Air_A,
        SCYTHE_SPECIAL_SniperStance_Air_B,
        SCYTHE_SPECIAL_SniperStance_Air_C,
        SCYTHE_SPECIAL_SniperStance_Air_J,
        SCYTHE_SPECIAL_SniperStance_Air_Exit,
        SCYTHE_SPECIAL_Buzzsaw_Grd_A,
        SCYTHE_SPECIAL_Buzzsaw_Grd_B,
        SCYTHE_SPECIAL_Buzzsaw_Grd_C,
        SCYTHE_ToGunMode = 87
    }
}