namespace rwby.core
{
    public enum RubyRoseStates : ushort
    {
        GRD_5L = 50,
        GRD_8L = 61,
        GRD_8LL = 62,
        GRD_2L = 64,
        GRD_2LL = 65,
        GRD_28L = 54,
        GRD_28L_Charged = 67,
        GRD_5H = 51,
        GRD_5HH = 52,
        GRD_8H = 53,
        GRD_8HH = 63,
        GRD_2H = 93,
        GRD_2H_held = 66,
        GRD_28H = 57,
        AIR_5L = 55,
        AIR_2L = 102,
        AIR_28L = 101,
        AIR_5H = 56,
        AIR_8H = 68,
        AIR_28H = 100,
        SCYTHE_SPECIAL_Buzzsaw_Ground = 58,
        SCYTHE_SPECIAL_Buzzsaw_Ground_L = 84,
        SCYTHE_SPECIAL_Buzzsaw_Ground_H = 85,
        SCYTHE_SPECIAL_Buzzsaw_Ground_U = 86,
        SCYTHE_SPECIAL_Buzzsaw_Aerial = 59,
        SCYTHE_SPECIAL_Buzzsaw_Aerial_End = 69,
        SCYTHE_SPECIAL_ScytheThrow = 60,
        SCYTHE_SPECIAL_ScytheThrow_L = 75,
        SCYTHE_SPECIAL_ScytheThrow_H = 103,
        SCYTHE_SPECIAL_ScytheThrow_U = 104,
        SCYTHE_SPECIAL_SniperStance_Grd_Enter = 70,
        SCYTHE_SPECIAL_SniperStance_Grd = 71,
        SCYTHE_SPECIAL_SniperStance_Grd_L = 72,
        SCYTHE_SPECIAL_SniperStance_Grd_H = 73,
        SCYTHE_SPECIAL_SniperStance_Grd_U = 74,
        //SCYTHE_SPECIAL_SniperStance_Grd_J = 75,
        SCYTHE_SPECIAL_SniperStance_Grd_Exit = 76,
        SCYTHE_SPECIAL_SniperStance_Air_Enter = 77,
        SCYTHE_SPECIAL_SniperStance_Air = 78,
        SCYTHE_SPECIAL_SniperStance_Air_L = 79,
        SCYTHE_SPECIAL_SniperStance_Air_H = 80,
        SCYTHE_SPECIAL_SniperStance_Air_U = 81,
        //SCYTHE_SPECIAL_SniperStance_Air_J = 82,
        SCYTHE_SPECIAL_SniperStance_Air_Exit = 83,
        change_moveset = 87,
        SCYTHE_SPECIAL_Ready_Grd = 88,
        SCYTHE_SPECIAL_Ready_Grd_A = 89,
        SCYTHE_SPECIAL_Ready_Grd_B = 90,
        SCYTHE_SPECIAL_Ready_Grd_C = 91,
        SCYTHE_SPECIAL_Ready_Air = 92,
        SCYTHE_SPECIAL_Gundash_Grd_L = 94,
        SCYTHE_SPECIAL_Gundash_Grd_H = 95,
        SCYTHE_SPECIAL_Gundash_Grd_J = 96,
        SCYTHE_SPECIAL_Gundash_Air_L = 98,
        SCYTHE_SPECIAL_Gundash_Air_H = 97,
        SCYTHE_SPECIAL_Gundash_Air_J = 99,
    }
}