namespace rwby.core
{
    public enum RubyRoseStates : ushort
    {
        GRD_5a = 50,
        GRD_8a = 61,
        GRD_8aA = 62,
        GRD_5b = 51,
        GRD_5bB = 52,
        GRD_8b = 53,
        GRD_8bB = 63,
        GRD_5c = 64,
        GRD_5cC = 65,
        GRD_2c = 54,
        GRD_2c_held = 93,
        GRD_8c = 66,
        AIR_5a = 55,
        AIR_5b = 56,
        AIR_8b = 68,
        AIR_5c = 57,
        SCYTHE_SPECIAL_Buzzsaw_Ground = 58,
        SCYTHE_SPECIAL_Buzzsaw_Ground_A = 84,
        SCYTHE_SPECIAL_Buzzsaw_Ground_B = 85,
        SCYTHE_SPECIAL_Buzzsaw_Ground_C = 86,
        SCYTHE_SPECIAL_Buzzsaw_Aerial = 59,
        SCYTHE_SPECIAL_ScytheThrow = 60,
        // ? = 67,
        SCYTHE_SPECIAL_Buzzsaw_Aerial_End = 69,
        SCYTHE_SPECIAL_SniperStance_Grd_Enter = 70,
        SCYTHE_SPECIAL_SniperStance_Grd = 71,
        SCYTHE_SPECIAL_SniperStance_Grd_A = 72,
        SCYTHE_SPECIAL_SniperStance_Grd_B = 73,
        SCYTHE_SPECIAL_SniperStance_Grd_C = 74,
        SCYTHE_SPECIAL_SniperStance_Grd_J = 75,
        SCYTHE_SPECIAL_SniperStance_Grd_Exit = 76,
        SCYTHE_SPECIAL_SniperStance_Air_Enter = 77,
        SCYTHE_SPECIAL_SniperStance_Air = 78,
        SCYTHE_SPECIAL_SniperStance_Air_A = 79,
        SCYTHE_SPECIAL_SniperStance_Air_B = 80,
        SCYTHE_SPECIAL_SniperStance_Air_C = 81,
        SCYTHE_SPECIAL_SniperStance_Air_J = 82,
        SCYTHE_SPECIAL_SniperStance_Air_Exit = 83,
        change_moveset = 87,
        SCYTHE_SPECIAL_Ready_Grd = 88,
        SCYTHE_SPECIAL_Ready_Grd_A = 89,
        SCYTHE_SPECIAL_Ready_Grd_B = 90,
        SCYTHE_SPECIAL_Ready_Grd_C = 91,
        SCYTHE_SPECIAL_Ready_Air = 92,
        SCYTHE_SPECIAL_Gundash_Grd = 94,
        SCYTHE_SPECIAL_Gundash_Air = 95,
        SCYTHE_SPECIAL_Gundash_Air_Dash = 96,
        SCYTHE_SPECIAL_Gundash_Air_Down = 97,
    }
}