// <auto-generated>
// Rewired Constants
// This list was generated on 1/1/2022 12:01:10 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace rwby {
    public static partial class Action {
        // Default
        // Gameplay
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Movement X")]
        public const int Movement_X = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Movement Y")]
        public const int Movement_Y = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Camera X")]
        public const int Camera_X = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Camera Y")]
        public const int Camera_Y = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Jump")]
        public const int Jump = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "A")]
        public const int A = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "B")]
        public const int B = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Block")]
        public const int Block = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Dash")]
        public const int Dash = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "C")]
        public const int C = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Lock-On")]
        public const int Lock_On = 11;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Ability Menu")]
        public const int Ability_Menu = 13;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Ability 1")]
        public const int Ability_1 = 14;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Ability 2")]
        public const int Ability_2 = 15;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Ability 3")]
        public const int Ability_3 = 16;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Ability 4")]
        public const int Ability_4 = 17;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Extra 1")]
        public const int Extra1 = 18;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Extra 2")]
        public const int Extra2 = 19;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Extra 3")]
        public const int Extra3 = 20;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Extra 4")]
        public const int Extra4 = 21;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Camera Switch")]
        public const int Camera_Switch = 22;
    }
}
